### ISSUE TITLE
Or sub-patterns

### ISSUE THREAD

**Issue by Enoumy** [alexsanc123/final_bs_optimizer#10]
You could rewrite

https://github.com/alexsanc123/final_bs_optimizer/blob/e6164ad4f9e67d8779c93677c16f4e995c37bdcd/bs_solver/lib/stdinout.ml#L55C1-L65C3

as:

```ocaml
  match String.lowercase input with
  | "t"
  | "true" 
  | "yes" 
  | "y"
  | "f" 
  | "no" 
  | "n"  -> true
  | "false" -> false 
  | _ -> false
;;
```

I think there's also a bug? Should "false" point to `false` instead of `true`?

**Comment by alexsanc123** [comment]
Thank you, we have fixed the pipes to make it more concise. Although, for this specific example our t or f is meant to weed out correct input, not whether it is actually supposed to be t or f! Thank you for the feedback :)
