### ISSUE TITLE
Probs a stale comment

### ISSUE THREAD

**Issue by Enoumy** [alexsanc123/final_bs_optimizer#4]
Heyo! I'm the ta whose name starts with "J", and I'm leaving some retroactive comments.

Small nitpick: It seems like this is a comment that was left behind. Would it be possible to delete?

https://github.com/alexsanc123/final_bs_optimizer/blob/e6164ad4f9e67d8779c93677c16f4e995c37bdcd/bs_solver/bin/main.ml#L6

**Comment by alexsanc123** [comment]
The commented out version allows us to test the game state without having to manually inout the card information. It will be removed very soon! Thank you!
