### ISSUE TITLE
Unnecessary module T

### ISSUE THREAD

**Issue by Enoumy** [alexsanc123/final_bs_optimizer#5]
Heyo!

Doing the `module T` trick is really only necessary when you are giving the type to a functor like `Comparable.Make`/`Hashable.Make`. It is not necessary alway, and not in this situation. Also happy to chat in-person on different contexts in which it's needed/not needed

https://github.com/alexsanc123/final_bs_optimizer/blob/e6164ad4f9e67d8779c93677c16f4e995c37bdcd/bs_solver/lib/all_players.ml#L3

**Comment by alexsanc123** [comment]
Thanks!
