### ISSUE TITLE
OCaml multiline strings

### ISSUE THREAD

**Issue by Enoumy** [alexsanc123/final_bs_optimizer#7]
Small suggestion/nitpick that might make things easier to write, OCaml has multiline strings with a bit of a weird sytnax that might be helpful here:

```ocaml
{|line1
line2
line3|}
```

https://github.com/alexsanc123/final_bs_optimizer/blob/e6164ad4f9e67d8779c93677c16f4e995c37bdcd/bs_solver/lib/game.ml#L39

**Comment by alexsanc123** [comment]
Thanks!
