### ISSUE TITLE
Really cool module!

### ISSUE THREAD

**Issue by Enoumy** [alexsanc123/final_bs_optimizer#8]
This module is really awesome. I really like the expect tests + the tail recursion + the general design. Feel free to mark this issue as closed after you've read it.

https://github.com/alexsanc123/final_bs_optimizer/blob/e6164ad4f9e67d8779c93677c16f4e995c37bdcd/bs_solver/lib/math_fun.ml#L3

**Comment by alexsanc123** [comment]
Thank you!
